apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-nodejs-app
  template:
    metadata:
      labels:
        app: simple-nodejs-app
    spec:
      containers:
        - name: simple-nodejs-app
          image: gcr.io/even-advantage-339309/simple-app-nodejs:latest
          ports:
            - containerPort: 3000