apiVersion: v1
kind: Service
metadata:
  name: simple-nodejs-app-deployment
spec:
  selector:
    app: simple-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer