name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: even-advantage-339309
  IMAGE_NAME: simple-app-nodejs
  CLUSTER_NAME: simple-nodejs-app
  ZONE: asia-southeast1-a

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Google Cloud
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
            gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }}
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
