name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Auth Google Cloud SDK
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}'

    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: 'Use gcloud CLI'
      run: 'gcloud auth configure-docker'

    - name: Build Docker image
      run: |
        export DOCKER_TAG=${{ github.sha }}
        export DOCKER_IMAGE=gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/simple-app-nodejs:${DOCKER_TAG}
        docker build -t $DOCKER_IMAGE .
        sudo -u $USER docker push $DOCKER_IMAGE

    # - name: Configure kubectl
    #   run: |
    #     gcloud container clusters get-credentials simple-nodejs-app --zone asia-southeast1-a --project even-advantage-339309
    #     kubectl config use-context gke_even-advantage-339309_asia-southeast1-a_simple-nodejs-app

    # - name: Set up Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '14.x'

    # - name: Install dependencies
    #   run: npm install

    # - name: Deploy to Kubernetes
    #   uses: appleboy/kubectl-action@master
    #   with:
    #     args: |
    #       set image deployment/simple-app-nodejs simple-app-nodejs=gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/simple-app-nodejs:${DOCKER_TAG}